import { randomBytes } from "crypto";
import { existsSync, writeFileSync } from "fs";
import { resolve } from "path";

// ── CLI Parsing ────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);

function flag(name: string): boolean {
  return args.includes(`--${name}`);
}

function option(name: string): string | undefined {
  const idx = args.indexOf(`--${name}`);
  if (idx === -1 || idx + 1 >= args.length) return undefined;
  return args[idx + 1];
}

if (flag("help") || flag("h")) {
  console.log(`
Usage: ${process.argv[0]} --mode <dev|prod> [--output <path>] [--force]

Options:
  --mode    dev or prod (required)
  --output  Output file path (default: docker/.env.dev or docker/.env.prod)
  --force   Overwrite existing file without prompting
  --help    Show this help message
`);
  process.exit(0);
}

const mode = option("mode");
if (!mode || !["dev", "prod"].includes(mode)) {
  console.error("Error: --mode must be 'dev' or 'prod'");
  process.exit(1);
}

const force = flag("force");

// ── Secret Generation ──────────────────────────────────────────────────────────

function generateSecret(bytes: number, encoding: BufferEncoding = "base64"): string {
  return randomBytes(bytes).toString(encoding);
}

// ── Environment Configuration ──────────────────────────────────────────────────

interface EnvConfig {
  POSTGRES_USER: string;
  POSTGRES_PASSWORD: string;
  POSTGRES_DB: string;
  DATABASE_URL: string;
  JWT_SECRET: string;
  PASSWORD_PEPPER: string;
  REGISTRATION_KEY: string;
}

function generateConfig(mode: "dev" | "prod"): EnvConfig {
  const pgUser = mode === "dev" ? "skillswap_dev" : "skillswap";
  const pgPassword = generateSecret(32, "base64url");
  const pgDb = mode === "dev" ? "skillswap_dev_db" : "skillswap_db";
  const pgHost = "postgres";
  const pgPort = 5432;

  return {
    POSTGRES_USER: pgUser,
    POSTGRES_PASSWORD: pgPassword,
    POSTGRES_DB: pgDb,
    DATABASE_URL: `postgresql://${pgUser}:${pgPassword}@${pgHost}:${pgPort}/${pgDb}`,
    JWT_SECRET: generateSecret(64, "base64"),
    PASSWORD_PEPPER: generateSecret(32, "base64"),
    REGISTRATION_KEY: generateSecret(16, "hex"),
  };
}

// ── Output Formatting ──────────────────────────────────────────────────────────

function formatEnv(config: EnvConfig): string {
  const lines: string[] = [
    `# Generated by envgen (${mode} mode)`,
    `# ${new Date().toISOString()}`,
    "",
    "# PostgreSQL",
    `POSTGRES_USER=${config.POSTGRES_USER}`,
    `POSTGRES_PASSWORD=${config.POSTGRES_PASSWORD}`,
    `POSTGRES_DB=${config.POSTGRES_DB}`,
    "",
    "# Application",
    `DATABASE_URL=${config.DATABASE_URL}`,
    `JWT_SECRET=${config.JWT_SECRET}`,
    `PASSWORD_PEPPER=${config.PASSWORD_PEPPER}`,
    `REGISTRATION_KEY=${config.REGISTRATION_KEY}`,
    "",
  ];
  return lines.join("\n");
}

// ── Main ───────────────────────────────────────────────────────────────────────

const config = generateConfig(mode as "dev" | "prod");
const envContent = formatEnv(config);

const defaultPath = mode === "dev" ? "docker/.env.dev" : "docker/.env.prod";
const outputPath = resolve(option("output") ?? defaultPath);

if (existsSync(outputPath) && !force) {
  console.error(`Error: ${outputPath} already exists. Use --force to overwrite.`);
  process.exit(1);
}

writeFileSync(outputPath, envContent, "utf-8");
console.log(`Wrote ${mode} environment to ${outputPath}`);
console.log("");
console.log(envContent);
