import { type IUser, type IProfile, type ISession, UserRole } from "shared/schema";

let uniqueId = 0;

export const users: IUser[] = [
    {
        id: (++uniqueId).toString(),
        handle: "nicholas.h",
        profileId: "1",
        createdAt: new Date("2026-01-01"),
        email: "nick@reversed.coffee",
        dob: new Date("2007-01-12"),
        role: UserRole.Admin,
        firstName: "Nicholas",
        lastName: "Hardenburgh",
        passwordHash: "password",
        passwordSalt: "salt",
    },
    {
        id: (++uniqueId).toString(),
        handle: "zachary.v",
        profileId: "2",
        createdAt: new Date("2026-01-01"),
        email: "zvp@skillswap.bpariverside.org",
        dob: new Date("2000-01-01"),
        role: UserRole.Admin,
        firstName: "Zachary",
        lastName: "Vanpatten",
        passwordHash: "password",
        passwordSalt: "salt",
    },
    {
        id: (++uniqueId).toString(),
        handle: "nicholas.g",
        profileId: "3",
        createdAt: new Date("2026-01-01"),
        email: "ngraham@skillswap.bpariverside.org",
        dob: new Date("2000-01-01"),
        role: UserRole.Admin,
        firstName: "Nicholas",
        lastName: "Graham",
        passwordHash: "password",
        passwordSalt: "salt",
    },
    {
        id: (++uniqueId).toString(),
        handle: "kyle.j",
        profileId: "4",
        createdAt: new Date("2026-01-01"),
        email: "kjones@skillswap.bpariverside.org",
        dob: new Date("2000-01-01"),
        role: UserRole.Admin,
        firstName: "Kyle",
        lastName: "Jones",
        passwordHash: "password",
        passwordSalt: "salt",
    },
];

export const profiles: IProfile[] = [
    {
        displayName: "Nicholas Hardenburgh",
        id: "1",
        userId: "1",
        avatarUrl: "https://github.com/reversed-coffee.png",
        tags: ["founder"],
        skills: ["DevOps", "Backend Development", "Cloud Architecture"],
        bio: "Engineer turned founder, passionate about shaping the future of tech education. Running SkillSwap to connect mentors and students worldwide, creating a vibrant community of learners and experts. Always eager to share knowledge and help others grow in their tech journeys.",
        stats: { sessionCount: 120, studentCount: 85, rating: 4.8 },
    },
    {
        displayName: "Zachary Vanpatten",
        id: "2",
        userId: "2",
        avatarUrl: "/images/avatar/zachary.v.png",
        tags: ["founder"],
        skills: ["Business Strategy", "Marketing", "Operations"],
        bio: "I handle the business side of things here, making sure SkillSwap runs smoothly and reaches more people. With a background in marketing and operations, I'm passionate about building communities and helping people connect. When I'm not working on SkillSwap, you can find me exploring new tech trends or enjoying a good book.",
        stats: { sessionCount: 95, studentCount: 70, rating: 4.7 },
    },
    {
        displayName: "Nicholas Graham",
        id: "3",
        userId: "3",
        avatarUrl: "/images/avatar/nicholas.g.jpg",
        tags: ["founder"],
        skills: ["Community Engagement", "Event Planning", "Public Speaking"],
        bio: "When you're within the SkillSwap community, you might have seen me hosting events or engaging with users. My role is to foster a welcoming and supportive environment for everyone involved. I believe in the power of community and am dedicated to creating spaces where people can connect, learn, and grow together. Outside of SkillSwap, I enjoy attending tech meetups and sharing insights on social media.",
        stats: { sessionCount: 80, studentCount: 150, rating: 4.9 },
    },
    {
        displayName: "Kyle Jones",
        id: "4",
        userId: "4",
        avatarUrl: "/images/avatar/kyle.j.png",
        tags: ["founder"],
        skills: ["Marketing", "Social Media", "Branding"],
        bio: "My focus is on spreading the word about SkillSwap and growing our community. We believe in the power of mentorship and are dedicated to connecting people who want to learn with those who want to teach. When I'm not working on marketing strategies, I enjoy exploring new tech trends and engaging with our users.",
        stats: { sessionCount: 70, studentCount: 120, rating: 4.85 },
    },
];

export const sessions: ISession[] = [
    /* Coding-oriented sessions */
    {
        id: "1",
        userId: "1",
        name: "Introduction to HTML & CSS: Building Your First Webpage",
        prereqs: "None",
        difficulty: "beginner",
        createdAt: new Date("2025-12-01T10:00:00Z"),
        eventDate: new Date("2025-12-15T18:00:00Z"),
    },
    {
        id: "2",
        userId: "1",
        name: "JavaScript Basics: From Variables to Functions",
        prereqs: "None",
        difficulty: "beginner",
        createdAt: new Date("2025-12-05T14:30:00Z"),
        eventDate: new Date("2025-12-20T20:00:00Z"),
    },
    {
        id: "3",
        userId: "1",
        name: "Web Frameworks 101: Astro for Beginners",
        prereqs: "Basic HTML/CSS/JS",
        difficulty: "intermediate",
        createdAt: new Date("2025-12-10T09:00:00Z"),
        eventDate: new Date("2025-12-25T15:00:00Z"),
    },
    {
        id: "4",
        userId: "1",
        name: "Version Control with Git: Getting Started",
        prereqs: "Command line basics",
        difficulty: "beginner",
        createdAt: new Date("2025-12-12T11:15:00Z"),
        eventDate: new Date("2025-12-30T19:00:00Z"),
    },

    /* Math-oriented sessions */
    {
        id: "5",
        userId: "2",
        name: "Algebra 101: Foundations for Success",
        prereqs: "None",
        difficulty: "beginner",
        createdAt: new Date("2025-12-02T10:00:00Z"),
        eventDate: new Date("2025-12-16T18:00:00Z"),
    },
    {
        id: "6",
        userId: "2",
        name: "Geometry Basics: Shapes, Angles, and Proofs",
        prereqs: "None",
        difficulty: "beginner",
        createdAt: new Date("2025-12-06T14:30:00Z"),
        eventDate: new Date("2025-12-21T20:00:00Z"),
    },
    {
        id: "7",
        userId: "2",
        name: "Trigonometry Essentials: Sine, Cosine, and Tangent",
        prereqs: "Basic Algebra and Geometry",
        difficulty: "intermediate",
        createdAt: new Date("2025-12-11T09:00:00Z"),
        eventDate: new Date("2025-12-26T15:00:00Z"),
    },
    {
        id: "8",
        userId: "2",
        name: "Calculus Introduction: Limits and Derivatives",
        prereqs: "Algebra and Trigonometry",
        difficulty: "advanced",
        createdAt: new Date("2025-12-13T11:15:00Z"),
        eventDate: new Date("2025-12-31T19:00:00Z"),
    },

    /* Photography-oriented sessions */

    {
        id: "9",
        userId: "3",
        name: "Photography Basics: Understanding Your Camera",
        prereqs: "None",
        difficulty: "beginner",
        createdAt: new Date("2025-12-03T10:00:00Z"),
        eventDate: new Date("2025-12-17T18:00:00Z"),
    },
    {
        id: "10",
        userId: "3",
        name: "Composition Techniques: Framing and Rule of Thirds",
        prereqs: "None",
        difficulty: "beginner",
        createdAt: new Date("2025-12-07T14:30:00Z"),
        eventDate: new Date("2025-12-22T20:00:00Z"),
    },
    {
        id: "11",
        userId: "3",
        name: "Portrait Photography: Lighting and Posing",
        prereqs: "Basic Photography Knowledge",
        difficulty: "intermediate",
        createdAt: new Date("2025-12-12T09:00:00Z"),
        eventDate: new Date("2025-12-27T15:00:00Z"),
    },
    {
        id: "12",
        userId: "3",
        name: "Digital Editing: Enhancing Your Photos with Software",
        prereqs: "Basic Photography, Composition, and Lighting",
        difficulty: "advanced",
        createdAt: new Date("2025-12-14T11:15:00Z"),
        eventDate: new Date("2025-12-29T19:00:00Z"),
    },

    /* Guitar-oriented sessions */

    {
        id: "13",
        userId: "4",
        name: "Guitar Basics: Chords and Strumming Patterns",
        prereqs: "None",
        difficulty: "beginner",
        createdAt: new Date("2025-12-04T10:00:00Z"),
        eventDate: new Date("2025-12-18T18:00:00Z"),
    },
    {
        id: "14",
        userId: "4",
        name: "Fingerstyle Guitar: Techniques and Practice",
        prereqs: "Basic Guitar Knowledge",
        difficulty: "intermediate",
        createdAt: new Date("2025-12-08T14:30:00Z"),
        eventDate: new Date("2025-12-23T20:00:00Z"),
    },
    {
        id: "15",
        userId: "4",
        name: "Guitar Soloing: Scales and Improvisation",
        prereqs: "Basic Guitar Knowledge",
        difficulty: "advanced",
        createdAt: new Date("2025-12-13T09:00:00Z"),
        eventDate: new Date("2025-12-28T15:00:00Z"),
    },
    {
        id: "16",
        userId: "4",
        name: "Songwriting with Guitar: Chord Progressions and Lyrics",
        prereqs: "Basic Guitar Knowledge",
        difficulty: "intermediate",
        createdAt: new Date("2025-12-15T11:15:00Z"),
        eventDate: new Date("2025-12-30T19:00:00Z"),
    }
];
